### PR TITLE
🐛 fix --asset-name flag

### LINKED ISSUE #858: 🐛 --asset-name is not rendered in Mondoo Platform
**Describe the bug**
`cnspec scan <target> --asset-name myasset` does not render in Mondoo Platform. This used to work in v8. I tested with `terraform-plan` and `aws`. 

**To Reproduce**

`cnspec scan aws --asset-name aws-demo-account`

**Expected behavior**

**Screenshots or CLI Output**
If applicable, add screenshots or the CLI output to help explain your problem.

**Desktop (please complete the following information):**

- OS: [e.g. macOS]
- OS Version: [e.g. 13.0]
- Browser if applicable: [e.g. Chrome, Firefox]
- Browser Version: [e.g. 106]

**Additional context**

### PR DESCRIPTION
**Pull request by mariuskimmina**
Closes #858 

```
cnspec scan ssh root@192.168.122.158 --ask-pass --config demo.agent.credentials.json --asset-name IAMTHEASSETNAMENOW
```

And here the result in console:

image

### CODE REVIEW

**Comment by mariuskimmina** [comment]
Marking as draft for now as I am not sure this works properly in all cases

**Comment by mariuskimmina** [comment]
Alternatively, we could also do something like this

```
  // if the flag --asset-name was used and there is only one asset, override the name
  if len(assets) == 1 {
		assetName := viper.GetString("asset-name")
    if assetName != "" {
      assets[0].asset.Name = viper.GetString("asset-name")
    }
  }
```

I am not really sure how `--asset-name` should behave if there is more than 1 asset

File: policy/scan/local_scanner.go [hunk 1]
```diff
@@ -374,14 +375,20 @@ func (s *LocalScanner) distributeJob(job *Job, ctx context.Context, upstream *up
 		}
 
 		// attach the asset details to the assets list
+		// also override asset name if flag --asset-name was used
 		for i := range assets {
 			log.Debug().Str("asset", assets[i].asset.Name).Strs("platform-ids", assets[i].asset.PlatformIds).Msg("update asset")
 			platformMrn := assets[i].asset.PlatformIds[0]
 			assets[i].asset.Mrn = platformAssetMapping[platformMrn].AssetMrn
 			assets[i].asset.Url = platformAssetMapping[platformMrn].Url
+			assetName := viper.GetString("asset-name")
```
Comment (preslavgerchev) [inline policy/scan/local_scanner.go]: we should pass that in from the caller of this func, we dont want to use viper here

ideally you want to attach this name to the root asset (cliAsset)

File: policy/scan/local_scanner.go [hunk 2]
```diff
@@ -391,6 +398,10 @@ func (s *LocalScanner) distributeJob(job *Job, ctx context.Context, upstream *up
 					return nil, false, multierr.Wrap(err, "failed to generate a random asset MRN")
 				}
 				cur.asset.Mrn = x.String()
+				assetName := viper.GetString("asset-name")
```
Comment (preslavgerchev) [inline policy/scan/local_scanner.go]: same comment as above

File: policy/scan/local_scanner.go (hunk 1 above)
Comment (preslavgerchev) [inline policy/scan/local_scanner.go]: on the question of how to work with this when there is more than a single asset i think we should either:
1. ignore the flag in that case
2. only apply it to the primary asset, targeted for connection. we return an asset and an inventory from the connect call. we should probably only apply the flag to the asset and not the inventory

@chris-rock any thoughts?

File: policy/scan/local_scanner.go (hunk 2 above)
Comment (preslavgerchev) [reply policy/scan/local_scanner.go]: actually, i don't think this is even needed. the `assets` list gets modified. above as well and the name gets assigned

File: policy/scan/local_scanner.go [hunk 3]
```diff
@@ -381,7 +381,7 @@ func (s *LocalScanner) distributeJob(job *Job, ctx context.Context, upstream *up
 			assets[i].asset.Url = platformAssetMapping[platformMrn].Url
 		}
 	} else {
-		// ensure we have non-empty asset MRNs
+		// ensure we have no non-empty asset MRNs
```
Comment (vjeffrey) [inline policy/scan/local_scanner.go]: i think the comment was ok as it was...we want to make sure the mrns are not empty, adding no there makes it seem like we want empty mrns

Comment (mariuskimmina) [reply policy/scan/local_scanner.go]: I added it because I thought that's the intention to **not** have non-empty mrns - maybe here it shines through that english is not my native language but to me it sounded wrong without the no

Comment (mariuskimmina) [reply policy/scan/local_scanner.go]: Changed it back

File: policy/scan/local_scanner.go [hunk 4]
```diff
@@ -395,6 +395,12 @@ func (s *LocalScanner) distributeJob(job *Job, ctx context.Context, upstream *up
 		}
 	}
 
+	// ensure that the root asset has keept his name from --asset-name
+	if job.Inventory.Spec.Assets[0].Name != assets[0].asset.Name {
```
Comment (preslavgerchev) [inline policy/scan/local_scanner.go]: i dont think we can guarantee the inventory's asset ordering here. should just attaching this to the `cliAsset` not be enough?

File: apps/cnspec/cmd/scan.go [hunk 5]
```diff
@@ -220,6 +221,14 @@ func getCobraScanConfig(cmd *cobra.Command, runtime *providers.Runtime, cliRes *
 		optAnnotations[k] = v
 	}
 
+	assetName, err := cmd.Flags().GetString("asset-name")
+	if err != nil {
+		log.Fatal().Err(err).Msg("failed to parse asset-name")
+	}
+	if assetName != "" {
+		cliRes.Asset.Name = assetName
```
Comment (preslavgerchev) [inline apps/cnspec/cmd/scan.go:229]: is it guaranteed that the `cliAsset` is not nil?

File: policy/scan/local_scanner.go (hunk 4 above)
Comment (mariuskimmina) [reply policy/scan/local_scanner.go]: It wasn't no, when just doing it on the cli asset it didn't work at all

File: apps/cnspec/cmd/scan.go (hunk 5 above)
Comment (mariuskimmina) [reply apps/cnspec/cmd/scan.go:229]: Not sure, I'll add a check

File: policy/scan/local_scanner.go [hunk 6]
```diff
@@ -395,6 +395,13 @@ func (s *LocalScanner) distributeJob(job *Job, ctx context.Context, upstream *up
 		}
 	}
 
+	// if there is exactly one asset, assure that the --asset-name is used
+	// TOOD: make it so that the --asset-name is set for the root asset only even if multiple assets are there
+	if len(assets) == 1 {
```
Comment (preslavgerchev) [inline policy/scan/local_scanner.go]: we should be doing this earlier, this is post SynchronizeAssets

there's a check for `len(assets == 0)` somewhere up, just before the sync call.  You can also use `assetList` as that loads up the job inventory:
```
if len(assets) == 1 && assetsList[0].Name != assets[0].Name) {
 ...
 }
 ```
also do please write a comment that this is a temp fix

**Comment by preslavgerchev** [comment]
lgtm!

**Review by preslavgerchev — APPROVED** [review]
