### PR TITLE
🧹 make status err reporting clearer

### LINKED ISSUE #365: Improve error message when service account has been revoked
**Describe the bug**
When the user has credentials setup in their config file, but the service account has been deleted the error message is unclear. We need to help users to understand that we tried to use the supplied credentials, but they are not valid. This error should also help to explain what could have caused this problem and what they need to do to get the asset registered again.

```
cnspec status
→ loaded configuration from /root/.config/mondoo/mondoo.yml using source default
→ Platform:	ubuntu
→ Version:	22.04
→ Hostname:	df6e4c259688
→ IP:		172.17.0.2
→ Time:		2023-02-22T01:17:20Z
→ Version:	7.18.0 (API Version: 7)
→ API ConnectionConfig:	https://us.api.mondoo.com
→ API Status:	SERVING
→ API Time:	2023-02-22T01:17:20Z
→ API Version:	7
→ Owner:	//captain.api.mondoo.app/spaces/stupefied-allen-438782
→ Client:	//agents.api.mondoo.app/spaces/stupefied-allen-438782/agents/2M4YxTcDjGjiWk8WlUc6zLQUJxz
→ Service Account:	//agents.api.mondoo.app/spaces/stupefied-allen-438782/serviceaccounts/2M4YxPvS3iLUIJ76SKogvSlyILG
→ client is registered
x could not connect to mondoo platform error="rpc error: code = Unauthenticated desc = request permission unauthenticated"
```

In an ideal world if we believe we have credentials in the config, but they don't work we should help the user to recover form this.

`The Mondoo Platform credentials provided at PATH/TO/CONFIG.yml didn't successfully authenticate with Mondoo Platform. This asset's service account might have been deleted. If this is the case, run cnspec logout --force and then register this asset with Mondoo Platform. For instructions, read https://mondoo.com/docs/cnspec/cnspec-adv-install/registration`

### PR DESCRIPTION
**Pull request by imilchev**
fixes #365

```
→ loaded configuration from /Users/ivanmilchev/Downloads/temp.json using source --config
→ Platform:     macos
→ Version:      13.3.1
→ Hostname:     Ivan-Milchev.local
→ IP:           192.168.2.4
→ Time:         2023-04-24T12:49:43+02:00
→ Version:      unstable (API Version: unstable)
→ API ConnectionConfig: https://us.api.mondoo.com
→ API Status:   SERVING
→ API Time:     2023-04-24T10:49:43Z
→ API Version:  8
! API versions do not match, please update the client
→ Owner:        //captain.api.mondoo.app/spaces/keen-banzai-154123
→ Client:       no managed client
→ Service Account:      //agents.api.mondoo.app/spaces/keen-banzai-154123/serviceaccounts/2OrwvXItmEV0Aue93mep5oPIiS4
→ client is registered
x The Mondoo Platform credentials provided at /Users/ivanmilchev/Downloads/temp.json didn't successfully authenticate with Mondoo Platform. Please re-authenticate e.g. via `cnspec login` with Mondoo Platform. For instructions, read https://mondoo.com/docs/install/registration. error="rpc error: code = Unauthenticated desc = request permission unauthenticated"
```

### CODE REVIEW

File: apps/cnspec/cmd/status.go [hunk 1]
```diff
@@ -193,7 +193,9 @@ func (s Status) RenderCliStatus() {
 	if s.Client.Registered && s.Client.PingPongError == nil {
 		log.Info().Msg(theme.DefaultTheme.Success("client authenticated successfully"))
 	} else {
-		log.Error().Err(s.Client.PingPongError).Msg("could not connect to mondoo platform")
+		log.Error().Err(s.Client.PingPongError).
+			Msgf("The Mondoo Platform credentials provided at %s didn't successfully authenticate with Mondoo Platform. Please re-authenticate e.g. via `cnspec login` with Mondoo Platform. For instructions, read https://mondoo.com/docs/install/registration.",
```
Comment (misterpantz) [inline apps/cnspec/cmd/status.go]:
```suggestion
			Msgf("The Mondoo Platform credentials provided at %s didn't successfully authenticate with Mondoo Platform. Please re-authenticate with the Mondoo Platform. To learn how, read: https://mondoo.com/docs/cnspec/cnspec-adv-install/registration/",
```

**Review by czunker — APPROVED** [review]
Nice. Thanks @imilchev
