### PR TITLE
🐛 Prevent panic in json output when all assets errored

### LINKED ISSUE #816: `cnspec scan k8s` panics with json output for some policies
**Describe the bug**
v8:
```
cnspec scan k8s -f ./kubernetes-1.24.mql.yaml -o json > /tmp/v8-gke-cis-k8s.json 
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
→ using service account credentials
→ discover related assets for 1 asset(s)
→ discovery option auto is used. This will detect the assets: cluster, cronjobs, daemonsets, deployments, ingresses, jobs, pods, replicasets, statefulsets
→ use cluster name from kube config cluster-name=gke_mondoo-edge_us-central1_mondoo-gke-cluster-2
→ resolved assets resolved-assets=273
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x81fcad2]

goroutine 1 [running]:
go.mondoo.com/cnspec/cli/reporter.ReportCollectionToJSON(0xc003b8b860, {0xb2bb400, 0xc004985470})
	/home/runner/_work/cnspec/cnspec/cli/reporter/json.go:64 +0x52
go.mondoo.com/cnspec/cli/reporter.(*Reporter).Print(0x7ffc3036814c?, 0xc003b8b860, {0xb2839c0, 0xc0000f2040})
	/home/runner/_work/cnspec/cnspec/cli/reporter/reporter.go:95 +0x392
go.mondoo.com/cnspec/apps/cnspec/cmd.printReports(0xa093bb6?, 0xc00342aaa0, 0x9b520c0?)
	/home/runner/_work/cnspec/cnspec/apps/cnspec/cmd/scan.go:715 +0xa5
go.mondoo.com/cnspec/apps/cnspec/cmd.glob..func22(0x0?, {0xc003394700, 0x0, 0x4}, 0x0?, 0x0?)
	/home/runner/_work/cnspec/cnspec/apps/cnspec/cmd/scan.go:417 +0x1a8
go.mondoo.com/cnquery/apps/cnquery/cmd/builder.kubernetesProviderCmd.func1(0x0?, {0xc003394700?, 0x0?, 0x0?})
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230920063559-f7739318c068/apps/cnquery/cmd/builder/builder.go:316 +0x28
go.mondoo.com/cnquery/apps/cnquery/cmd/builder/common.KubernetesProviderCmd.func2(0xc002fb5500?, {0xc003394700?, 0x4?, 0xa09059b?})
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230920063559-f7739318c068/apps/cnquery/cmd/builder/common/common.go:295 +0x75
github.com/spf13/cobra.(*Command).execute(0xc003002300, {0xc0033946c0, 0x4, 0x4})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0x102d82e0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
go.mondoo.com/cnspec/apps/cnspec/cmd.Execute()
	/home/runner/_work/cnspec/cnspec/apps/cnspec/cmd/root.go:79 +0x1a
main.main()
	/home/runner/_work/cnspec/cnspec/apps/cnspec/cnspec.go:6 +0xf
```

v9:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x1181ef2]

goroutine 1 [running]:
go.mondoo.com/cnspec/v9/cli/reporter.ReportCollectionToJSON(0xc005cba820, {0x17c4d58, 0xc0008770b0})
	/home/runner/_work/cnspec/cnspec/cli/reporter/json.go:67 +0x52
go.mondoo.com/cnspec/v9/cli/reporter.(*Reporter).Print(0x7ffc3073e120?, 0xc005cba820, {0x17b9280, 0xc00007c030})
	/home/runner/_work/cnspec/cnspec/cli/reporter/reporter.go:131 +0x392
go.mondoo.com/cnspec/v9/apps/cnspec/cmd.printReports(0xc000798dc0?, 0xc000798dc0, 0x0?)
	/home/runner/_work/cnspec/cnspec/apps/cnspec/cmd/scan.go:379 +0xa7
go.mondoo.com/cnspec/v9/apps/cnspec/cmd.glob..func13(0x0?, 0x17ce3d0?, 0x22e1a20?)
	/home/runner/_work/cnspec/cnspec/apps/cnspec/cmd/scan.go:135 +0x139
go.mondoo.com/cnquery/v9/cli/providers.setConnector.func2(0xc00097e100?, {0xc000057b40?, 0x0, 0x4})
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery/v9@v9.0.0/cli/providers/providers.go:472 +0x96e
```

This seems related to the policy. The same command worked for the CIS GKE policy and the Mondoo Kubernetes Security policy.

**To Reproduce**

1. Run scan against GKE with k8s 1.24 CIS policy
2. Note the error

**Expected behavior**
I'd expect no panic, even when the actual cause might be in the policy.

**Desktop (please complete the following information):**

- cnspec v9 and v8.28.4

**Additional context**
This seems also to be independent of GKE. I got the same panic with my local minikube.

It also happens with the ./kubernetes-1.23.mql.yaml policy.

### PR DESCRIPTION
**Pull request by czunker**
Fixes #816

### CODE REVIEW

File: cli/reporter/json.go [hunk 1]
```diff
@@ -64,15 +64,20 @@ func ReportCollectionToJSON(data *policy.ReportCollection, out shared.OutputHelp
 		return nil
 	}
 
-	qid2mrn := make(map[string]string, len(data.Bundle.Queries))
+	var qid2mrn map[string]string
```
Comment (chris-rock) [inline cli/reporter/json.go:67]: Can we add a test case that validates the output of json?

Comment (czunker) [reply cli/reporter/json.go:67]: Done.

I added two different tests. Please check, whether that's what you had in mind.

File: apps/cnspec/cmd/scan.go [hunk 2]
```diff
@@ -132,6 +133,7 @@ var scanCmdRun = func(cmd *cobra.Command, runtime *providers.Runtime, cliRes *pl
 		log.Fatal().Err(err).Msg("failed to run scan")
 	}
 
+	logger.DebugDumpJSON("report", report)
```
Comment (czunker) [inline apps/cnspec/cmd/scan.go:136]: I needed also this to generate the same debug output we had in v8.

**Review by chris-rock — APPROVED** [review]
