### PR TITLE
🐛 Convert implicit props into explicit props

### LINKED ISSUE #1843: Implicit Properties are not supported
cnquery v12 introduced the ability to have implicit properties.

The following fails to compile:
```
policies:
  - uid: implicit-props
    name: implicit-props policy 1
    version: "1.0.0"
    authors:
      - name: Mondoo
        email: hello@mondoo.com
    groups:
      - filters: return true
        queries:
          - uid: query-1
    props:
      - uid: xtesting
        mql: return true

queries:
  - uid: query-1
    title: testing
    mql: props.xtesting == true
```

```
cnspec policy lint ./policy-new.yaml.mql          x1
→ lint policy bundle file=./policy-new.yaml.mql
→ installing provider 'ai' version=12.0.1
→ successfully installed ai provider path=/Users/atomic111/.config/mondoo/providers/ai version=12.0.1
  RULE ID                       LEVEL    FILE                 LINE  MESSAGE
  bundle-compile-error          error    policy-new.yaml.mql  1     Could not compile policy bundle: failed to validate query '//local.cnspec.io/run/local-execution/queries/query-1': failed to compile query 'props.xtesting == true': failed to compile: cannot find property 'xtesting', please define it first

  policy-required-tags-missing  warning  policy-new.yaml.mql  2     policy 'implicit-props' does not contain the required tag `mondoo.com/category`
  policy-required-tags-missing  warning  policy-new.yaml.mql  2     policy 'implicit-props' does not contain the required tag `mondoo.com/platform`
FTL invalid policy bundle
```

The issue is that when we compile, we try to look up global properties by name. However, they are stored in a map by mrn. I think we would also need to modify the resolver to pass those props. Right now, it assumes that all props are explicit.

I think the way this needs to work is during bundle compilation, we need to resolve implicit props into explicit props. The example above needs to somehow turn into:
```
policies:
  - uid: implicit-props
    name: implicit-props policy 1
    version: "1.0.0"
    authors:
      - name: Mondoo
        email: hello@mondoo.com
    groups:
      - filters: return true
        queries:
          - uid: query-1
    props:
      - mrn: //local.cnspec.io/policies/implicit-props/properties/xtesting
        mql: return true
        for:
        - mrn: //local.cnspec.io/queries/query-1/properties/xtesting

queries:
  - uid: query-1
    title: testing
    mql: props.xtesting == true
    props:
    - mrn: //local.cnspec.io/queries/query-1/properties/xtesting
      type: boolean
```

### PR DESCRIPTION
**Pull request by jaym**
cnquery v12 introduced the ability to have implicit properties.

The following failed to compile:
```
policies:
  - uid: implicit-props
    name: implicit-props policy 1
    version: "1.0.0"
    authors:
      - name: Mondoo
        email: hello@mondoo.com
    groups:
      - filters: return true
        queries:
          - uid: query-1
    props:
      - uid: xtesting
        mql: return true

queries:
  - uid: query-1
    title: testing
    mql: props.xtesting == true
```

This change converts implicit props to explicit props when the bundle is uploaded. A query can lookup from any of its parents. It goes up the chain in order, using the first matching prop. If one is found, we create the prop on the query. The matching prop on the parent references it through `for`.

The bundle above becomes:
```
policies:
  - uid: implicit-props
    name: implicit-props policy 1
    version: "1.0.0"
    authors:
      - name: Mondoo
        email: hello@mondoo.com
    groups:
      - filters: return true
        queries:
          - uid: query-1
    props:
      - mrn: //local.cnspec.io/policies/implicit-props/properties/xtesting
        mql: return true
        for:
        - mrn: //local.cnspec.io/queries/query-1/properties/xtesting

queries:
  - uid: query-1
    title: testing
    mql: props.xtesting == true
    props:
    - mrn: //local.cnspec.io/queries/query-1/properties/xtesting
      type: boolean
```

Fixes #1843

Requires https://github.com/mondoohq/cnquery/pull/6011

### CODE REVIEW

File: policy/bundle.go [hunk 1]
```diff
@@ -1365,19 +1402,19 @@ func (c *bundleCache) precompileQuery(query *explorer.Mquery, policy *Policy) *e
...
-			lookup, ok := c.lookupProps[prop.Mrn]
-			if !ok {
-				c.errors = append(c.errors, fmt.Errorf("property %s not found in bundle for query %s", prop.Mrn, query.Mrn))
-				return nil
-			}
-			query.Props[i] = lookup.Property
-		}
-	}
+	// for i := range query.Props {
+	// 	prop := query.Props[i]
```
Comment (imilchev) [inline policy/bundle.go]: Can we delete this now?

Comment (jaym) [reply policy/bundle.go]: yep, fixed in cnquery

File: policy/bundle.go [hunk 2]
```diff
@@ -1399,33 +1422,167 @@ func (c *bundleCache) precompileQuery(query *explorer.Mquery, policy *Policy) *e
...
+		query:      query,
+		parents:    parents,
+		nameToProp: propsMap,
+		errors:     []error{},
+	}, nil
+}
+
+func (r *QueryPropsResolver) Get(name string) *llx.Primitive {
+	// Check explicitlyl defined properties
+	for propName, queryProp := range r.nameToProp {
```
Comment (czunker) [inline policy/bundle.go]: Why do we have to loop?
`nameToProp` is a map. Couldn't we look up by the name directly?

File: policy/bundle.go [hunk 3]
```diff
@@ -1399,33 +1422,167 @@ func (c *bundleCache) precompileQuery(query *explorer.Mquery, policy *Policy) *e
...
+	r.walkParents(func(p hasProps) bool {
+		for _, prop := range p.GetProps() {
+			propName, err := explorer.GetPropName(prop.Mrn)
+			if err != nil {
+				continue
+			}
+			if propName == name {
+				found.mrn = prop.Mrn
+				found.prop = prop
+				return true
```
Comment (czunker) [inline policy/bundle.go:1490]: What if the prop is also used in another query?

I'm not sure I fully understood your comment and code in this case.
Could the same prop be used in multiple queries?

Comment (jaym) [reply policy/bundle.go:1490]: We pick the first one, walking up the chain. So if a query is a variant, we check its parent and then the policy. The use case not covered is if 2 policies reference the same query and each define the property.
