### PR TITLE
🐛 Don't exit on single asset policy mismatch

### LINKED ISSUE #48: error scanning k8s cluster
```
cnspec scan k8s -f ../../cnspec-policies/core/mondoo-kubernetes-security.mql.yaml
→ loaded configuration from /Users/chris/.config/mondoo/mondoo.yml using source default
! Scanning with local policy bundles will switch into --incognito mode by default. Your results will not be sent upstream.
! invalid github token via environment variable, ignoring it
→ discover related assets for 1 asset(s)
→ use cluster name from kube config cluster-name=minikube
→ resolved assets resolved-assets=11
→ connecting to asset K8S Cluster minikube (api)
→ connecting to asset kube-system/coredns (k8s-object)
→ client> send all results asset=//policy.api.mondoo.com/assets/2FlOXKk5iHVE91HlS3VTuesypL3
→ connecting to asset kube-system/coredns-64897985d-b7t87 (k8s-object)
→ client> send all results asset=//policy.api.mondoo.com/assets/2FlOXO8uDDyIl0kV1yJGuCNmopG
→ connecting to asset kube-system/etcd-minikube (k8s-object)
→ client> send all results asset=//policy.api.mondoo.com/assets/2FlOXOU0ibh3ysBgIRmpVZsGxcc
→ connecting to asset kube-system/kube-apiserver-minikube (k8s-object)
→ client> send all results asset=//policy.api.mondoo.com/assets/2FlOXN84ugoY5TIyG9n1TuFPW6Z
→ connecting to asset kube-system/kube-controller-manager-minikube (k8s-object)
→ client> send all results asset=//policy.api.mondoo.com/assets/2FlOXOd9Td7XCgaWYpHtajibRuE
→ connecting to asset kube-system/kube-proxy-f4djp (k8s-object)
→ client> send all results asset=//policy.api.mondoo.com/assets/2FlOXP3754Klh2cTx8UzdInG0nJ
→ connecting to asset kube-system/kube-scheduler-minikube (k8s-object)
→ client> send all results asset=//policy.api.mondoo.com/assets/2FlOXP28wfPDZiWG8kYbb1EVSMR
→ connecting to asset kube-system/storage-provisioner (k8s-object)
→ client> send all results asset=//policy.api.mondoo.com/assets/2FlOXOAOISkLFkSFf6XS5931MAs
→ connecting to asset kube-system/kube-proxy (k8s-object)
→ client> send all results asset=//policy.api.mondoo.com/assets/2FlOXQqJelKFwylrWhLJdEhp4K3
→ connecting to asset kube-system/coredns-64897985d (k8s-object)
→ client> send all results asset=//policy.api.mondoo.com/assets/2FlOXKseCVFsEDkjFfBMjyF62uT
FTL failed to run scan error="1 error occurred:\n\t* rpc error: code = InvalidArgument desc = asset does not match any of the activated policies\n\n"
```

The expectation is that it displays this as an asset error not as fatal error.

### PR DESCRIPTION
**Pull request by czunker**
Report on assets where we have something to report and skip the others.

Fixes #48

Signed-off-by: Christian Zunker <christian@mondoo.com>

### CODE REVIEW

File: apps/cnspec/cmd/scan.go [hunk 1]
```diff
@@ -507,7 +507,7 @@ func RunScan(config *scanConfig) *policy.ReportCollection {
 			PolicyFilters: config.PolicyNames,
 		})
 	if err != nil {
-		log.Fatal().Err(err).Msg("failed to run scan")
+		log.Warn().Err(err).Msg("failed to run scan")
```
Comment (chris-rock) [inline apps/cnspec/cmd/scan.go]: Removing log.Fatal here means we do not get an proper exit code when things really fail

File: policy/scan/local_scanner.go [hunk 2]
```diff
@@ -183,7 +183,14 @@ func (s *LocalScanner) RunAssetJob(job *AssetJob) {
 			job.connection = m
 			results, err := s.runMotorizedAsset(job)
 			if err != nil {
-				job.Reporter.AddScanError(job.Asset, err)
+				if statusError, ok := status.FromError(err); ok {
```
Comment (chris-rock) [inline policy/scan/local_scanner.go]: I do not think we should add special error handling here. Instead we should track the error on a per asset basis
